# Generated by Django 5.0.14 on 2025-07-07 13:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUsers',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('aud', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('email_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_token', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_token', models.CharField(blank=True, max_length=255, null=True)),
                ('recovery_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_change_token_new', models.CharField(blank=True, max_length=255, null=True)),
                ('email_change', models.CharField(blank=True, max_length=255, null=True)),
                ('email_change_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_sign_in_at', models.DateTimeField(blank=True, null=True)),
                ('raw_app_meta_data', models.JSONField(blank=True, null=True)),
                ('raw_user_meta_data', models.JSONField(blank=True, null=True)),
                ('is_super_admin', models.BooleanField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('phone_change', models.TextField(blank=True, null=True)),
                ('phone_change_token', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_change_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_change_token_current', models.CharField(blank=True, max_length=255, null=True)),
                ('email_change_confirm_status', models.SmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('banned_until', models.DateTimeField(blank=True, null=True)),
                ('reauthentication_token', models.CharField(blank=True, max_length=255, null=True)),
                ('reauthentication_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sso_user', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_model', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'indexes': [models.Index(fields=['id'], name='users_instance_id_idx'), models.Index(fields=['is_sso_user'], name='users_is_sso_user_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='authusers',
            constraint=models.CheckConstraint(check=models.Q(('email_change_confirm_status__gte', 0), ('email_change_confirm_status__lte', 2)), name='users_email_change_confirm_status_check'),
        ),
    ]
