# Generated by Django 5.0.14 on 2025-07-09 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetrial',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 10, 22, 58, 818931, tzinfo=datetime.timezone.utc)),
        ),
    ]
